version: '3.7'
#user:universe
#date:10/02/23
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    build: .
    ports:
      - "8081:8081"
      - "50000:50000"
    
    environment:
      - JENKINS_OPTS=--httpPort=8081
    user: root
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - mynet

volumes:
  jenkins_home:
    driver: local

networks:
  mynet: